# Generated by Django 2.1.4 on 2018-12-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181227_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a category of auction (e.g. Charity, Electronics etc.)', max_length=200),
        ),
    ]
