# Generated by Django 2.1.4 on 2018-12-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20181227_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='is_tender',
            new_name='is_on_auction',
        ),
        migrations.AlterField(
            model_name='lot',
            name='duration',
            field=models.DurationField(help_text='Enter a duration time eg 3d 2:20:10'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='start_price',
            field=models.DecimalField(decimal_places=1, help_text='Enter a starting price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lot',
            name='step',
            field=models.DecimalField(decimal_places=1, help_text='Enter a starting price', max_digits=5),
        ),
    ]
